library("ggplot2")
library("readxl")
library("dplyr")
library("tidyverse")
library("ggpubr")
library("ape")
library("lme4")
library("gplots")
library("plotly")
library("tidyr")
library("vegan")
library("data.table")
library("stringr")

#the goal here is to probe the distribution of fluxes within fluxpath_subsystems. 
#data used here was generated by analysis of MSI output in 06.16.21_combinding_TDpointonefive_flux_values_from_MSI_runs.py 

#loosely based on 09.30.21_Hale2018_fluxpath_analysis_at_median_subsystem_level.R
#and 09.30.21_Burns2015_analyzing_fluxpath_subsystem_composition

##########Preliminary steps
rm(list = ls()) #clear out environment as needed. 
setwd("/Users/adamo010/Documents/MICOM_CRC_FBA/Individual_specific_microbiomes/Analyzing_MICOM_communities_Hale2018/") 

##########Step 1: import data and adjust factors
analyzed_fluxpaths <- read_csv("09.02.21_Hale2018_fluxes_with_metadata_longform.csv")
analyzed_fluxpaths$host_subject_id <- as.factor(analyzed_fluxpaths$host_subject_id)
#colnames(analyzed_metabolites) #print column names as needed

##########Step 2: do some preliminary graphing
#drop unnecessary columns
analyzed_fluxpaths_subset <- subset(analyzed_fluxpaths, select = -c(...1, fluxpath_description, fluxpath_formula))
analyzed_fluxpaths_subset_noNANs <- analyzed_fluxpaths_subset[!is.na(analyzed_fluxpaths_subset$fluxpath_amount),]
#really need to just rename tumor/normal column to Description
analyzed_fluxpaths_subset_noNANs <- analyzed_fluxpaths_subset_noNANs %>% rename(Description = normal_adjacent_or_tumor_tissue_specimen)

#try a graph. THis one graphs all fluxpath activity within the Alanine and aspartate metabolism subsystem, with different colored boxplots for each
#tumor and normal sample.
ggplot(subset(analyzed_fluxpaths_subset_noNANs, fluxpath_subsystem %in% c("Alanine and aspartate metabolism")),
       aes(x=fluxpath_name, y= fluxpath_amount, fill=Description)) +
  geom_boxplot() +
  geom_jitter(position=position_jitter(0.2)) +
  labs(title= "Fluxpath activity within Alanine and aspartate metabolism subsystem") +
  scale_x_discrete(name ="Fluxpath name") +
  theme(axis.text.x = element_text(angle = 60, hjust=1)) +
  scale_y_continuous(name = "Flux, mmmol/(gDW * h)") +
  theme(legend.position="none", plot.title = element_text(hjust=0.5, vjust=2, size=12))

#Let's look at the subsystems that we previously identified as significantly different (ish) between tumor and normal samples. 
#Tyrosine metabolism, Urea cycle, tRNA Charging, Alanine and aspartate metabolism
ggplot(subset(analyzed_fluxpaths_subset_noNANs, fluxpath_subsystem %in% c("Alanine and aspartate metabolism")),
       aes(x=fluxpath_name, y= fluxpath_amount, fill=Description)) +
  geom_boxplot() +
  geom_jitter(position=position_jitter(0.2)) +
  labs(title= "Fluxpath activity within Alanine and aspartate metabolism subsystem") +
  scale_x_discrete(name ="Fluxpath name") +
  theme(axis.text.x = element_text(angle = 60, hjust=1)) +
  scale_y_continuous(name = "Flux, mmmol/(gDW * h)") +
  theme(legend.position="none", plot.title = element_text(hjust=0.5, vjust=2, size=12))

#need some counts of # flux pathways within each subsystem. 
analyzed_fluxpaths_filtering_df <- analyzed_fluxpaths_subset_noNANs %>%  #create a new dataframe by filtering the old one
  #mutate(count_of_nonzeros = rowSums(.[3:4]!=0)) %>% #create a new column, count_of_nonzeroes, that counts # nonzero values in columns 3 and 4 for each row
  group_by(fluxpath_subsystem) %>% #group by the column of interest
  summarize(n = length(unique(fluxpath_name))) %>% #calculates the number of unique fluxpath_names within a subsystem and saves the value as n
  mutate(n) #add n as a new column in the dataframe
#create a new dataframe that merges the old and new dataframes
analyzed_fluxpaths_filter_added <- dplyr::inner_join(analyzed_fluxpaths_subset_noNANs, analyzed_fluxpaths_filtering_df, by= "fluxpath_subsystem")

#now, should be able to extract a DF of fluxpath_subsystem and n for graphing.
fluxpaths_count_df <- analyzed_fluxpaths_filter_added[,c('fluxpath_subsystem', 'n')]
fluxpaths_count_df <- unique(fluxpaths_count_df)
#drop NA values- these represent an order of magnitude more subsystems than any other named subsystem
fluxpaths_count_df <- fluxpaths_count_df %>% drop_na(fluxpath_subsystem)

#plot
ggplot(data= fluxpaths_count_df, aes(x= reorder(fluxpath_subsystem, -n), y=n, color= fluxpath_subsystem, fill= fluxpath_subsystem)) +
  geom_bar(stat= "identity", width=0.5) +
  labs(title = expression("Number of fluxpaths within each subsystem, Hale2018 data")) +
  theme(plot.title = element_text(hjust=0.5), plot.margin = unit(c(0.1,0.1,0.1,0.1), "cm"), 
        axis.text.x = element_text (size = 5, angle = 45, hjust = 1)) +
  scale_y_continuous(name = "Number of fluxpaths") +
  scale_x_discrete(name = "Subsystem name") +
  #scale_fill_brewer(palette = "Dark2") +
  #scale_color_brewer(palette = "Dark2") +
  theme(legend.position = "none") +
  guides(fill="none")
#graph notes:
#reorder sorts the x-axis as high->low y-axis values

######Interlude#######
#now, I would like to figure out the percentage of fluxpaths that fall into each subsystem. And graph it. 
#number of unique fluxpaths:
fluxpaths_unique <- unique(analyzed_fluxpaths$fluxpath_name)# 6269 total.
#recalculate fluxpaths_count_df, but keep na in this time.
fluxpaths_count_df2 <- analyzed_fluxpaths_filter_added[,c('fluxpath_subsystem', 'n')]
fluxpaths_count_df2 <- unique(fluxpaths_count_df2)
#sanity check: sum the n column
sum(fluxpaths_count_df2$n) #5264 What the hell. 
#hang on, let's check something...
fluxpaths_unique2 <- unique(analyzed_fluxpaths_subset_noNANs$fluxpath_name) #5264
#all right, that's fine. There must be some fluxpaths that aren't active in any sample. it's fine to remove them. 
#now, add a new percentage column to DF
fluxpaths_count_df2$perc <- (((fluxpaths_count_df2$n)/5264)*100)
#so, na makes up 36% of flux pathways. Great.

fluxpaths_count_df2 <- fluxpaths_count_df2 %>%  #create a new dataframe by filtering the old one
  summarize(perc = (n/5762)*100) %>% #calculates the percentage of fluxpaths that fall within each subsystem
  mutate(perc) #add n as a new column in the dataframe
#eh, this isn't that interesting.

####################

#figure out what % of fluxpaths are in, say, the top five subsystems (by size)
sum(fluxpaths_count_df$n) #3374.
fluxpaths_count_df$perc <- (((fluxpaths_count_df$n)/3374)*100)
#okay. 54% of reactions fall within the top five subsystems. That's... useful information, I guess?

#let's try a lollipop chart
ggplot(data= fluxpaths_count_df, aes(x= reorder(fluxpath_subsystem, n), y=n, color= fluxpath_subsystem, fill= fluxpath_subsystem)) +
  geom_segment( aes(x=reorder(fluxpath_subsystem, n), xend=reorder(fluxpath_subsystem, n), y=0, yend=n)) +
  geom_point(size=1, alpha=0.6) +
  labs(title = expression("Number of fluxpaths within each\n subsystem, Hale2018 data")) +
  theme_light() +
  coord_flip() +
  theme(plot.title = element_text(hjust=0.5), plot.margin = unit(c(1,0.5,0.1,0.1), "cm")) +
  #theme(panel.grid.major.y = element_blank(), panel.border = element_blank(), axis.ticks.y = element_blank()) +
  theme(legend.position = "none") +
  scale_y_continuous(name = "Number of fluxpaths") +
  scale_x_discrete(name = "Subsystem name")

#let's try a lollipop chart with only the top 10 subsystems. AND< I want to graph the ranges within each subsystem across samples
#basically, bottom end of lollipop is min # pathways per subsystem within one patient, and top end of lollipop is max.
#how should I do this? go back to analyzed_fluxpaths_subset_noNANs
analyzed_fluxpaths_filtering_PBI <- analyzed_fluxpaths_subset_noNANs %>%  #create a new dataframe by filtering the old one
  #mutate(count_of_nonzeros = rowSums(.[3:4]!=0)) %>% #create a new column, count_of_nonzeroes, that counts # nonzero values in columns 3 and 4 for each row
  group_by(Sample_ID, fluxpath_subsystem) %>% #group by the column of interest
  summarize(n = length(unique(fluxpath_name))) %>% #calculates the number of unique fluxpath_names within a subsystem and saves the value as n
  mutate(n) #add n as a new column in the dataframe

#awesomesauce: this creates a dataframe with counts of # fluxpaths within each subsystem within each sample_id
#create a new df that has the max, min, median, and mean # fluxpaths within each subsystem within each sample_id
#aw fuck, why do a lollipop when you can do a boxplot?
#NOTE: drop NA here, it screws with everything.
analyzed_fluxpaths_filtering_PBI2 <- analyzed_fluxpaths_filtering_PBI %>% drop_na(fluxpath_subsystem)

ggplot(analyzed_fluxpaths_filtering_PBI2, aes(x=fluxpath_subsystem, y= n, fill=fluxpath_subsystem)) +
  geom_boxplot() +
  geom_jitter(position=position_jitter(0.2)) +
  labs(title= "Distribution of # fluxpaths within each subsystem, Burns2015 data") +
  scale_x_discrete(name ="Subsystem name") +
  theme(axis.text.x = element_text(angle = 60, hjust=1)) +
  scale_y_continuous(name = "Number of fluxpaths") +
  theme(legend.position="none", plot.title = element_text(hjust=0.5, vjust=2, size=12))

#okay, make both the boxplot and the lollipop plot again, but only with top five subsystems
fluxpaths_count_df_top5 <- fluxpaths_count_df %>%                                     
  arrange(desc(n)) %>% 
  slice(1:5)

#need to filter here by only including fluxpath_subsystems in fluxpaths_count_df_top5 
top_5_subsystems <- pull(fluxpaths_count_df_top5, fluxpath_subsystem) #create a vector for filtering
analyzed_fluxpaths_filtering_PBI2_top5  <- filter(analyzed_fluxpaths_filtering_PBI2, fluxpath_subsystem %in% top_5_subsystems) #10/10

#now graph. 
ggplot(analyzed_fluxpaths_filtering_PBI2_top5, aes(x=fluxpath_subsystem, y= n, fill=fluxpath_subsystem)) +
  geom_boxplot() +
  geom_jitter(position=position_jitter(0.2)) +
  labs(title= "Distribution of # fluxpaths within each subsystem,\n Burns2015 data, top five subsystems only") +
  scale_x_discrete(name ="Subsystem name") +
  theme(axis.text.x = element_text(angle = 60, hjust=1)) +
  scale_y_continuous(name = "Number of fluxpaths") +
  theme(legend.position="none", plot.title = element_text(hjust=0.5, vjust=2, size=12))

#NOTE: need this, but by tumor/normal
analyzed_fluxpaths_subset_noNANs_top5 <- filter(analyzed_fluxpaths_subset_noNANs, fluxpath_subsystem %in% top_5_subsystems) #filter
PID_by_SI_key <- analyzed_fluxpaths_subset_noNANs_top5[, c('Sample_ID', 'host_subject_id', "Description")] #extract sampleID/patient_blind_ID columns
PID_by_SI_key <- unique(PID_by_SI_key) #remove duplicates
#create a new dataframe that merges the old and new dataframes
analyzed_fluxpaths_filtering_PBI2_top5_withDesc <- dplyr::inner_join(analyzed_fluxpaths_filtering_PBI2_top5, PID_by_SI_key, by= "Sample_ID")
analyzed_fluxpaths_filtering_PBI2_top5_withDesc <- unique(analyzed_fluxpaths_filtering_PBI2_top5_withDesc) #that was weird. Anyway....

ggplot(analyzed_fluxpaths_filtering_PBI2_top5_withDesc, aes(x=fluxpath_subsystem, y= n, fill=Description)) +
  geom_boxplot() +
  geom_jitter(position=position_jitter(0.2), size=1) +
  labs(title= "Activity of fluxpaths within top five most populated fluxpath subsystems") +
  scale_x_discrete(name ="Fluxpath name") +
  theme(axis.text.x = element_text(angle = 60, hjust=1)) +
  scale_y_continuous(name = "Flux, mmmol/(gDW * h)") +
  theme(legend.position="none", plot.title = element_text(hjust=0.5, vjust=2, size=12))

#great. but we actually want the most significantly different fluxpaths. 
#Tyrosine metabolism, Urea cycle, tRNA Charging, Alanine and aspartate metabolism
sig_diff_subsystems <- c("Tyrosine metabolism", "Urea cycle", "tRNA Charging", "Alanine and aspartate metabolism")
analyzed_fluxpaths_subset_noNANs_sigdiff <- filter(analyzed_fluxpaths_subset_noNANs, fluxpath_subsystem %in% sig_diff_subsystems) #filter
PID_by_SI_key2 <- analyzed_fluxpaths_subset_noNANs_sigdiff[, c('Sample_ID', 'host_subject_id', "Description")] #extract sampleID/patient_blind_ID columns
PID_by_SI_key2 <- unique(PID_by_SI_key2) #remove duplicates
analyzed_fluxpaths_filtering_PBI2_sigdiffs  <- filter(analyzed_fluxpaths_filtering_PBI2, fluxpath_subsystem %in% sig_diff_subsystems) #10/10
#create a new dataframe that merges the old and new dataframes
analyzed_fluxpaths_filtering_PBI2_sigdiff_withDesc <- dplyr::inner_join(analyzed_fluxpaths_filtering_PBI2_sigdiffs, PID_by_SI_key2, by= "Sample_ID")
analyzed_fluxpaths_filtering_PBI2_sigdiff_withDesc <- unique(analyzed_fluxpaths_filtering_PBI2_sigdiff_withDesc) #that was weird. Anyway....

ggplot(analyzed_fluxpaths_filtering_PBI2_sigdiff_withDesc, aes(x=fluxpath_subsystem, y= n, fill=Description)) +
  geom_boxplot() +
  geom_jitter(position=position_jitter(0.2), size=1) +
  labs(title= "Number of fluxpaths within most significantly different median\n fluxpath subsystem values, tumor v normal") +
  scale_x_discrete(name ="Fluxpath name") +
  theme(axis.text.x = element_text(angle = 60, hjust=1)) +
  scale_y_continuous(name = "Number of fluxpaths in each subsystem") +
  theme(legend.position="none", plot.title = element_text(hjust=0.5, vjust=2, size=12))

#absolutely terrible. NO WAIT, this is actually a good thing. It means we're not biasing by different pathway counts between tumor and normal samples.

#NOW we graph
ggplot(analyzed_fluxpaths_subset_noNANs_sigdiff, aes(x=fluxpath_subsystem, y= fluxpath_amount, fill=Description)) +
  geom_boxplot() +
  #geom_jitter(position=position_jitter(0.2), size=1) +
  labs(title= "Activity of fluxpaths within significantly different median\n fluxpath subsystem values, tumor v normal") +
  scale_x_discrete(name ="Fluxpath name") +
  theme(axis.text.x = element_text(angle = 60, hjust=1)) +
  scale_y_continuous(name = "Flux, mmmol/(gDW * h)") +
  theme(legend.position="none", plot.title = element_text(hjust=0.5, vjust=2, size=12))

#for lollipop, more interested in bottom
fluxpaths_count_df_bottom <- fluxpaths_count_df %>%                                     
  arrange(desc(n)) %>% 
  slice(6:n())
#graph
ggplot(data= fluxpaths_count_df_bottom, aes(x= reorder(fluxpath_subsystem, n), y=n, color= fluxpath_subsystem, fill= fluxpath_subsystem)) +
  geom_segment( aes(x=reorder(fluxpath_subsystem, n), xend=reorder(fluxpath_subsystem, n), y=0, yend=n)) +
  geom_point(size=1, alpha=0.6) +
  labs(title = expression("Number of fluxpaths within each subsystem,\n Hale2018 data, bottom 88 pathways only")) +
  theme_light() +
  coord_flip() +
  theme(panel.grid.major.y = element_blank(), panel.border = element_blank(), axis.ticks.y = element_blank()) +
  theme(legend.position = "none") +
  scale_y_continuous(name = "Number of fluxpaths") +
  scale_x_discrete(name = "Subsystem name")


